" required by vim latex-suite
" filetype plugin on
" set grepprg=grep\ -nH\ $*
" filetype indent on
" let g:tex_flavor='latex'

" if filereadable(expand("~/.vimrc_background"))
  " let base16colorspace=256
  " source ~/.vimrc_background
" endif

" jellybeans
let g:jellybeans_overrides = {
\    'background': { 'ctermbg': 'none', '256ctermbg': 'none' },
\}
colorscheme jellybeans

nnoremap <leader>lc :w<CR>:!pdflatex %<CR>
nnoremap <leader>lv :!xdg-open %:r.pdf &<CR><CR>
